//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armazem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Armazem()
        {
            this.Pedido_usuario = new HashSet<Pedido_usuario>();
            this.Produto_armazem = new HashSet<Produto_armazem>();
            this.Usuario = new HashSet<Usuario>();
            this.Veiculo = new HashSet<Veiculo>();
            this.PedidoFinal_usuario = new HashSet<PedidoFinal_usuario>();
        }
    
        public int idArmazem { get; set; }
        public string nome_armazem { get; set; }
        public string logradouro_armazem { get; set; }
        public string numlogradouro_armazem { get; set; }
        public string largura_armazem { get; set; }
        public string altura_armazem { get; set; }
        public string profundidade_armazem { get; set; }
        public string telefone_armazem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_usuario> Pedido_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produto_armazem> Produto_armazem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Veiculo> Veiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoFinal_usuario> PedidoFinal_usuario { get; set; }
    }
}
