//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplyProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupplyProject_dbEntities : DbContext
    {
        public SupplyProject_dbEntities()
            : base("name=SupplyProject_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Armazem> Armazem { get; set; }
        public virtual DbSet<Fornecedor> Fornecedor { get; set; }
        public virtual DbSet<Produto_armazem> Produto_armazem { get; set; }
        public virtual DbSet<Produto_fornecedor> Produto_fornecedor { get; set; }
        public virtual DbSet<Produto_produtor> Produto_produtor { get; set; }
        public virtual DbSet<Produtor> Produtor { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Veiculo> Veiculo { get; set; }
        public virtual DbSet<DemandaFinal_produtor> DemandaFinal_produtor { get; set; }
        public virtual DbSet<StatusDemanda> StatusDemanda { get; set; }
        public virtual DbSet<PedidoFinal_usuario> PedidoFinal_usuario { get; set; }
        public virtual DbSet<StatusPedido> StatusPedido { get; set; }
        public virtual DbSet<EnvioFornecedor> EnvioFornecedor { get; set; }
        public virtual DbSet<StatusEnvioFornecedor> StatusEnvioFornecedor { get; set; }
        public virtual DbSet<EnvioArmarazem> EnvioArmarazem { get; set; }
        public virtual DbSet<StatusEnvioArmazem> StatusEnvioArmazem { get; set; }
    }
}
