//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto_armazem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto_armazem()
        {
            this.DemandaFinal_produtor = new HashSet<DemandaFinal_produtor>();
        }
    
        public int idProduto_armazem { get; set; }
        public string nome_prodA { get; set; }
        public double preco_prodA { get; set; }
        public double peso_prodA { get; set; }
        public double largura_prodA { get; set; }
        public double altura_prodA { get; set; }
        public double profundidade_prodA { get; set; }
        public int quantidade_prodA { get; set; }
        public int Usuario_idUsuario { get; set; }
        public int Armazem_idArmazem { get; set; }
    
        public virtual Armazem Armazem { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandaFinal_produtor> DemandaFinal_produtor { get; set; }
    }
}
