//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veiculo()
        {
            this.EnvioFornecedor = new HashSet<EnvioFornecedor>();
            this.EnvioArmarazem = new HashSet<EnvioArmarazem>();
        }
    
        public int idVeiculo { get; set; }
        public string tipo_veiculo { get; set; }
        public string custo_frete { get; set; }
        public string capacidade_peso { get; set; }
        public string capacidade_altura { get; set; }
        public string capacidade_largura { get; set; }
        public string capacidade_profundidade { get; set; }
        public string placa_veiculo { get; set; }
        public int Armazem_idArmazem { get; set; }
    
        public virtual Armazem Armazem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvioFornecedor> EnvioFornecedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvioArmarazem> EnvioArmarazem { get; set; }
    }
}
